### ISSUE TITLE
关于面试

### ISSUE THREAD

**Issue by marzk** [marzk/blog#2]
### 电话面试

这次电话面试运气比较差，因为网络竟然突然欠费了，尴尬。  
面试三个方面HTMLCSS、JS，还有简单写了一个代码。

---
#### HTMLCSS
1. DOCTYPE的作用以及混杂模式下具体表现
   - 告知浏览器以什么样的文档类型来解析这个文档
   - 混杂模式以宽松的向后兼容的方式显示，模拟老式浏览器的行为；主要是盒模型的区别
2. 具体的兼容性问题及如何解决
   1. png24的图片在IE6下出现背景，转换为PNG8
   2. 浏览器的默认内外边距不同，设置 \* { margin: 0; padding: 0;} 
   3. ie6双外边距BUG，元素浮动后，如果设置了margin-left或margin-right，则外边距会加倍，设置 `_display: inline` 即可
3. 块级元素行内元素区别
4. CSS选择器权值

``` CSS
/* count 1 if the declaration is from is a 'style' attribute rather than a rule with a selector, 0 otherwise (= a) (In HTML, values of an element's "style" attribute are style sheet rules. These rules have no selectors, so a=1, b=0, c=0, and d=0.)
 * count the number of ID attributes in the selector (= b)
 * count the number of other attributes and pseudo-classes in the selector (= c)
 * count the number of element names and pseudo-elements in the selector (= d)
*/
```
1. 定位
#### JS
1. 作用域
2. this
3. 内存泄露
### 一面

面试的问题就这几个方向，关于自己、关于HTMLCSS、关于JS、关于jQuery、关于项目

---
#### 关于自己

**自我介绍：**
**为什么辞职：**
**为什么来北京：**
**为什么选择拉勾网：**
**自己遇到的最难的问题及如何解决：**
**能否接受加班：**
**自己的优缺点：**
**关注了最近什么样的新技术：**

---
#### 关于HTMLCSS

**CSS文件是否会阻塞加载：**
**attribute和property的区别：**
**为什么checkbox等的attribute不管用：**
**CSS HACK：**

``` CSS
.bb{
    background-color:#f1ee18;/*所有识别*/
    .background-color:#00deff\9; /*IE6、7、8识别*/
    +background-color:#a200ff;/*IE6、7识别*/
    _background-color:#1e0bd1;/*IE6识别*/ 
} 
```

**position：**
**HTML5的几个API：**`sessionstorage`与`localstorage`的区别
**从输入网址到显示在用户浏览器端的过程：**
**兼容性问题：**
**清除浮动：**

---
#### 关于js

**如何对js进行优化：**
**闭包是什么以及优缺点：**
**类继承：**
**原型继承：**
**跨域问题：**
**作用域：**
**this：**
**cookie：**cookie有限制，最大为4096字节。优点：在cookie存放不敏感数据；缺点：长度限制，安全性问题。
**null和undefiend区别：**
1. null转换为数值为0，undefined转换为数值为NaN
2. 未定义变量为undefined，未存在的对象表示null

还有一道很难的js题

``` javascript
var length = 10;
function fn() {
    alert(this.length);
}
var obj = {
    length: 5,
    method: function (fn) {
        fn();  // 什么值？
        arguments[0](); // 什么值？
    }
};
obj.method(fn);
```

---
#### 关于jQuery

**如何对jQuery进行优化：**
**$.fn是什么：**

---
#### 关于项目

**如何对整个项目的前端进行优化：**

---
### 二面
1. 有几种获取到其他文件并利用的方式
2. CSS垂直居中的几种方式

``` CSS
/*
 * 查了一下，除了传统的常用的负外边距与translate的方法
 * 还有一种利用绝对定位内block元素的计算公式来垂直居中
*/
.b {
    position: absolute;
    top: 0; right: 0; bottom: 0; left: 0;
    margin: auto
}
```
### 总结

关于拉勾网的这次面试，充分体现了一点，表达能力太差以及写代码的经验还不够，很多东西常常用，但是没表达出来。但还好，这次踩过的坑，下次都不会踩了。

---
### 二面

与之前面试以基本知识为主，这次的面试以介绍经历与其中的具体技术为主。最后三个笔试题分别考察url的提取、有序数组的操作与状态方程。
### 三面

三面以介绍自己为主，这部分自己做的还是很差，很多东西说的太笼统。兴趣、爱好、有成就感的事等等。这次面试的最后以一道笔试题为结束。不得不说，这道笔试题答的太差了。首先是思考的不深入，太急躁了，思考了一步就说出来了，应该整体思考完毕再说。

在往回走的路上才想到字符级的优化方法。这方面的能力需要加强。
